### ISSUE TITLE
"Questions Answered" in level closing

### ISSUE THREAD

**Issue by kiwim0n** [archiedb/archie#51]
When trying to close a level, one of the checks says "questions answered". If any of the three "Notes" areas on the level edit page are empty, this check fails. But it is not clear how to fix it. The mouse pointer seems to indicate that "Questions answered?" is click-able, but nothing happens if I click on it. Going back to the level edit page, the sub-heading for that section is "Notes" rather than "Questions".

Maybe the solution is to change "Questions answered?" to "Level Notes completed?" or something like that.

Also I think it would be good to indicate somehow on the level edit form that the Notes fields are required for level closure.

**Comment by vollmerk** [comment]
@nyersa - What's your call on this? I agree it's confusing. rename the question or add an explanation?

**Comment by nyersa** [comment]
Lets go ahead and change it to "level notes completed?". kiwim0n is also on to something with the required fields for level closure, however its not just here but in records as well. What do you think about specifying which fields are required for a form to be closed across all forms? Maybe put an asterisk or something next to them?
