### ISSUE TITLE
how to get to a graphical web browser in the VM

### ISSUE THREAD

**Issue by benmarwick** [archiedb/archie#65]
I can get up to step 3 of the [VM installation instructions](http://archiedb.com/wp-content/uploads/2015/03/archie_installation_virtualbox.pdf) but then I'm not sure how to get to the desktop or a graphical web browser. I can do `sensible-browser 10.2.0.15` to get to a text web browser, but `echo $DESKTOP_SESSION` returns nothing, so it seems like there's no desktop env on the VM. What's the best way to proceed? thanks!

**Comment by nyersa** [comment]
Hi Ben, we updated the VM image recently so I am not positive that those
instructions are 100% up to date... I will go through it this evening and
let you know for sure.

On Wed, Jul 29, 2015 at 4:51 PM, Ben Marwick <notifications@github.com>
wrote:

> I can get up to step 3 of the VM installation instructions
> <http://archiedb.com/wp-content/uploads/2015/03/archie_installation_virtualbox.pdf>
> but then I'm not sure how to get to the desktop or a graphical web browser.
> I can do sensible-browser 10.2.0.15 to get to a text web browser, but echo
> $DESKTOP_SESSION returns nothing, so it seems like there's no desktop env
> on the VM. What's the best way to proceed? thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archiedb/archie/issues/65>.
>



-- 
Thanks,

Alex Nyers
Department of Anthropology
Oregon State University
http://oregonstate.academia.edu/AlexNyers

**Comment by nyersa** [comment]
Hi Ben, to save on space and machine requirements we do not currently have
a GUI desktop installed on the VM image. You should however not need it to
get the ip address (the step you are stuck on) to access Archie, as you
will use a web browser on your host computer to access it (or other
computers that are on your network). To get to the ip address of the Archie
server (it will be different from your computers regular IP), I need to you
to do two things.

1. Open virtualbox but do not start Archie. Instead, highlight the Archie
install, then click Settings, then Network. from here, make sure that
"Attached to" is set to "bridged adapter". Click OK.

2. Start the Archie install, and login as root. Then type "ifconfig". Next
to "eth0" you should see "inet addr:" followed by a set of numbers. For
example, "inet addr:192.168.0.12" This is the Archie install's ip address.
On your main computer, open a web browser and type this in at the address
field.

Let us know how it works. I will be uploading a new image this evening that
displays the IP address of the Archie server upon boot to make it a little
easier.

On Wed, Jul 29, 2015 at 4:58 PM, Alex Nyers <nyersa@gmail.com> wrote:

> Hi Ben, we updated the VM image recently so I am not positive that those
> instructions are 100% up to date... I will go through it this evening and
> let you know for sure.
>
> On Wed, Jul 29, 2015 at 4:51 PM, Ben Marwick <notifications@github.com>
> wrote:
>
>> I can get up to step 3 of the VM installation instructions
>> <http://archiedb.com/wp-content/uploads/2015/03/archie_installation_virtualbox.pdf>
>> but then I'm not sure how to get to the desktop or a graphical web browser.
>> I can do sensible-browser 10.2.0.15 to get to a text web browser, but echo
>> $DESKTOP_SESSION returns nothing, so it seems like there's no desktop
>> env on the VM. What's the best way to proceed? thanks!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/archiedb/archie/issues/65>.
>>
>
>
>
> --
> Thanks,
>
> Alex Nyers
> Department of Anthropology
> Oregon State University
> http://oregonstate.academia.edu/AlexNyers
>



-- 
Thanks,

Alex Nyers
Department of Anthropology
Oregon State University
http://oregonstate.academia.edu/AlexNyers

**Comment by benmarwick** [comment]
Hi Alex,
 
Thanks for your quick reply. After setting Network as you suggest, and logging in, my eth0 inet address doesn't quite seem right, as you can see in the screenshots below. How do you suggest I proceed? 

thanks again,

Ben

![clipboard14](https://cloud.githubusercontent.com/assets/1262179/8981956/caf43016-36e6-11e5-8f61-2033e8a70ea6.png)


![archie-production](https://cloud.githubusercontent.com/assets/1262179/8981895/2d8b6880-36e6-11e5-8d8b-5721f92543e4.png)

**Comment by nyersa** [comment]
Hi Ben, I'm betting you don't have a DHCP server running on your network
that will hand out an ip address to your Archie server. I am going to have
you tweak your settings one more time to get around this. Alternatively you
can download a new image (http://archiedb.com/Archie-Production.zip)
<http://archiedb.com/Archie-Production.zip> that we just uploaded that has
these settings tweaked for you.

1. With the Archie server shut down and in virtualbox manager, to the the
network settings and switch back to NAT.

settings --> network --> attached to: NAT

Also, while you are there, we are going to change port forwarding slightly
(click on the port forwarding button.) You should currently see one rule
listed, change it to look like the following, and add a second rule (by
clicking on the green plus symbol).

[image: Inline image 3]


Once you set your port forwarding rules, click ok and start up your Archie
server again. After Archie boots you should be able to access it on your
workstation by opening a web browser and going to the following url:

http://localhost:7080

Let me know how it works for you.

On Thu, Jul 30, 2015 at 4:15 AM, Ben Marwick <notifications@github.com>
wrote:

> Hi Alex,
>
> Thanks for your quick reply. After setting Network as you suggest, and
> logging in, my eth0 inet address doesn't quite seem right, as you can see
> in the screenshots below. How do you suggest I proceed?
>
> thanks again,
>
> Ben
>
> [image: clipboard14]
> <https://cloud.githubusercontent.com/assets/1262179/8981956/caf43016-36e6-11e5-8f61-2033e8a70ea6.png>
>
> [image: archie-production]
> <https://cloud.githubusercontent.com/assets/1262179/8981895/2d8b6880-36e6-11e5-8d8b-5721f92543e4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/archiedb/archie/issues/65#issuecomment-126276555>.
>



-- 
Thanks,

Alex Nyers
Department of Anthropology
Oregon State University
http://oregonstate.academia.edu/AlexNyers

**Comment by nyersa** [comment]
Hi Ben, looks like that screenshot did not come through, here it is:
![screenshot from 2015-07-30 10 44 09](https://cloud.githubusercontent.com/assets/3900770/8990553/f5b55882-36a7-11e5-83f8-8179c980d3a4.png)

**Comment by benmarwick** [comment]
Thanks very much, that's solved the problem!
